sudo: required
language: generic
services: docker
tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=tests/*/main.tex
- packages=lipsum, blindtext
script:
- chmod +x .travis/travis-texbuild.sh
- .travis/travis-texbuild.sh
env:
  global:
    secure: u6vSoxcW99cGefjPsbLmBneDuvJhfsfo6bNSYaYL+0TjX2S5HTfnbDqsnk9jJTjFsLRpynR2I2+X57I59psTGoOvpqgSE4o4Mlj1fmoTgYD11G/xzFHZD/vahwsgkxQheYJQZDPDOvegCtC6DS2rArP317spD1ih9QATkVaqQWlJklnMOfYrasA2wFdA4gzMr/CkzbtZeIPuQPCrwvFW/GxOSTIdQ6K0FgiMv7tdqheUNBhgb5BMtqb7tD/n3vkEfZoiZldJXG8ww+DHjxGt9s/hCjXurwspzOvgC+tvVs5kY+5RWvoOkTtyMZgkwdhA6kko0eWEKcpknCYc8qYSKnddO7Upc52KGXWwLoT+MFt7JoYeSvsFi8ezP0x5n0uHJLmsbw4kX4D46EBXg/pcDDM2gOWq1w9Dsblmsx8OedLN1Qad9gU93vZbky981u8FxQox/hoLyzuc+UvtZNVNusqi57wED2MyR9F1qt6HPueGWRri3r1xGoyN5kw4ydflwoURWn5UI6XHcmbB+K7WuVnrvxa/KZBs5Ru+OcXTEr1z99yarIgxOiaEWJ2Vrc/sO5WvznNP81dfZfYvVcR7QZHxsibXpOQDa0kPkO/uklykKfzzUlkxf4O0or/XYyIwUeYxz8OJ90NfLB/hUH8duftzdjdUIoxeD4xr7scvZus=
