name: build_cv
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: set up git repository
        uses: actions/checkout@v2
      - name: compile_cv
        uses: dante-ev/latex-action@master
        with:
                root_file: main.tex
                compiler: xelatex
                args: -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: move pdf to compiled folder
        run: mv ./main.pdf ./compiled/cv.pdf
      - name: push files back
        uses: mikeal/publish-to-github-action@master
        env:
                GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
      - name: publish to github pages
        uses: peaceiris/actions-gh-pages@v2.0.0
        env:
                ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                PUBLISH_BRANCH: gh-pages
                PUBLISH_DIR: ./compiled
