name: build_cv
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: compile_cv2
        uses: dante-ev/latex-action@master
        with:
                root_file: main.tex
                compile: lualatex
                args: -interaction=nonstopmode
      - name: compile_cv3
        uses: dante-ev/latex-action@master
        with:
                root_file: main.tex
                compile: xelatex
                args: -interaction=nonstopmode
